/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(chat)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(chat)'}/new-room` | `/new-room`; params?: Router.UnknownInputParams; } | { pathname: `${'/(chat)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(chat)'}/[chat]` | `/[chat]`, params: Router.UnknownInputParams & { chat: string | number; } } | { pathname: `${'/(chat)'}/settings/[chat]` | `/settings/[chat]`, params: Router.UnknownInputParams & { chat: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(chat)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(chat)'}/new-room` | `/new-room`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(chat)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(chat)'}/[chat]` | `/[chat]`, params: Router.UnknownOutputParams & { chat: string; } } | { pathname: `${'/(chat)'}/settings/[chat]` | `/settings/[chat]`, params: Router.UnknownOutputParams & { chat: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(chat)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(chat)'}/new-room${`?${string}` | `#${string}` | ''}` | `/new-room${`?${string}` | `#${string}` | ''}` | `${'/(chat)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(chat)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(chat)'}/new-room` | `/new-room`; params?: Router.UnknownInputParams; } | { pathname: `${'/(chat)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `${'/(chat)'}/${Router.SingleRoutePart<T>}` | `/${Router.SingleRoutePart<T>}` | `${'/(chat)'}/settings/${Router.SingleRoutePart<T>}` | `/settings/${Router.SingleRoutePart<T>}` | { pathname: `${'/(chat)'}/[chat]` | `/[chat]`, params: Router.UnknownInputParams & { chat: string | number; } } | { pathname: `${'/(chat)'}/settings/[chat]` | `/settings/[chat]`, params: Router.UnknownInputParams & { chat: string | number; } };
    }
  }
}
